version: 1
datastore:
  filename: stats.sqlite
scheduler:
  period_sec: 5
phlevel:
  url: http://acit3855.westus3.cloudapp.azure.com/storage/phlevel?timestamp=
chlorinelevel:
  url: http://acit3855.westus3.cloudapp.azure.com/storage/chlorinelevel?timestamp=
